name: Build and test
on:
  push:
    branches:
      - 'main'
      - 'vs_890_javaize_cosmos_spike'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: 'Build and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Set up Temurin Java 17'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - name: 'Compile production code'
        run: |
          ./gradlew compileJava
      - name: 'Compile test code'
        run: |
          ./gradlew compileTestJava
      - name: run-tests
        run: |
          ./gradlew test
